apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: httpd
  name: rhpds-only
  namespace: simple-app
spec:
  clusterSelector:
    matchLabels:
      cluster-id: rhpds
