apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-clusters
  namespace: apache-test
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      cloud: "Amazon"
  clusterReplicas: 1
